name: expensenoted
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.4

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  http_interceptor: ^1.0.2
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  path_provider: ^2.0.9
  intl: ^0.17.0
  lottie: ^1.2.2
  flutter_datetime_picker:
    git: https://github.com/Realank/flutter_datetime_picker.git
  flutter_dotenv: ^5.0.2
  sticky_grouped_list: ^2.1.0
  syncfusion_flutter_charts: ^19.4.56
  dots_indicator: ^2.1.0
  url_launcher: ^6.0.20
  month_year_picker: ^0.1.0+1
  googleapis: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/custom/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/categories/
    - assets/lottie/
    - assets/custom/
    - assets/guideline gif/

  fonts:
    - family: Open Sans Condensed
      fonts:
        - asset: assets/fonts/OpenSansCondensed-Bold.ttf
          weight: 300
        - asset: assets/fonts/OpenSansCondensed-Light.ttf
          weight: 700
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
